/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DatePicker: typeof import('./components/common/DatePicker.vue')['default']
    DialogAddMenu: typeof import('./components/UI/AppManagement/Menu/DialogAddMenu.vue')['default']
    DialogFormBranch: typeof import('./components/UI/Master/Branch/DialogFormBranch.vue')['default']
    DialogFormHeader: typeof import('./components/UI/AppManagement/Menu/DialogFormHeader.vue')['default']
    DialogFormMenu: typeof import('./components/UI/AppManagement/Menu/DialogFormMenu.vue')['default']
    DialogFormRole: typeof import('./components/UI/AppManagement/Role/DialogFormRole.vue')['default']
    DialogFormRoleMenu: typeof import('./components/UI/AppManagement/RoleMenu/DialogFormRoleMenu.vue')['default']
    DialogFormUser: typeof import('./components/UI/AppManagement/User/DialogFormUser.vue')['default']
    DialogStructureMenu: typeof import('./components/UI/AppManagement/Menu/DialogStructureMenu.vue')['default']
    FormDataMenu: typeof import('./components/UI/AppManagement/Menu/FormDataMenu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
